# settings.yaml
input_directory: "./data/input"
output_directory: "./data/output"
archive_directory: "./data/archive"
log_directory: "./logs"
pandas_threshold_mb: 200
rows_per_file: 4999
max_retries: 3
retry_delay_seconds: 10
max_concurrent_files: 4  # Number of concurrent files to process
